version: "3"

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/products-microservices-426815/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/products-microservices-426815/image-registry/products-ms
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: europe-west12-docker.pkg.dev/products-microservices-426815/image-registry/orders-ms
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}
  # # # ====================
  # # # Payments MS
  # # # ====================
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/products-microservices-426815/image-registry/payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:3003
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}

  # # ====================
  # # Auth MS
  # # ====================
  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: europe-west12-docker.pkg.dev/products-microservices-426815/image-registry/auth-ms
    ports:
      - ${AUTH_MS_PORT}:3004
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${DATABASE_URL_AUTH_MS}
      - JWT_SECRET=${JWT_SECRET}
